/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Servicios.rolServicio;
import Servicios.usuarioService;
import entidades.Usuario;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author agust
 */
public class MenuInicio extends javax.swing.JFrame {

    usuarioService us = new usuarioService();
    rolServicio rs = new rolServicio();

    /**
     * Creates new form MenuInicio
     */
    public MenuInicio() {
        initComponents();
        FillComboBox(ComboUsuarioaEditar, us.dao.TraerTodosUsuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelTipoCesion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        TxtUsuarioCrear = new javax.swing.JTextField();
        TxtContraseñaCrear = new javax.swing.JTextField();
        BtnCrearUsuario = new javax.swing.JButton();
        LblCrearUsuario = new javax.swing.JLabel();
        ComboRol = new javax.swing.JComboBox<>();
        LblTxtCrearUsuario = new javax.swing.JLabel();
        LblTxtCrearContraseña = new javax.swing.JLabel();
        LblSeleccionarRol = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        TxtContraseñaEditar = new javax.swing.JTextField();
        LblEditarUsuario = new javax.swing.JLabel();
        ComboUsuarioaEditar = new javax.swing.JComboBox<>();
        LblUsuarioTextFieldEditar = new javax.swing.JLabel();
        LblContraseñaEditar = new javax.swing.JLabel();
        LblEditarCombo = new javax.swing.JLabel();
        ComboRolEditar = new javax.swing.JComboBox<>();
        BtnEditarUsuario = new javax.swing.JButton();
        LblContraseñaEditar1 = new javax.swing.JLabel();
        TxtContraseñaAnterior = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenuPrincipal = new javax.swing.JMenu();
        MitmVenta = new javax.swing.JMenuItem();
        MimtStock = new javax.swing.JMenuItem();
        MitmCesion = new javax.swing.JMenuItem();
        MitmDevolucion = new javax.swing.JMenuItem();
        MitmConsultas = new javax.swing.JMenuItem();
        MitmSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(33, 33, 33));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        LabelTipoCesion.setBackground(new java.awt.Color(33, 33, 33));
        LabelTipoCesion.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        LabelTipoCesion.setForeground(new java.awt.Color(255, 255, 255));
        LabelTipoCesion.setText(disposemessange());

        jPanel2.setBackground(new java.awt.Color(33, 33, 33));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 33, 33)));

        TxtUsuarioCrear.setBackground(new java.awt.Color(51, 51, 51));
        TxtUsuarioCrear.setForeground(new java.awt.Color(255, 255, 255));
        TxtUsuarioCrear.setBorder(null);
        TxtUsuarioCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuarioCrearActionPerformed(evt);
            }
        });

        TxtContraseñaCrear.setBackground(new java.awt.Color(51, 51, 51));
        TxtContraseñaCrear.setForeground(new java.awt.Color(255, 255, 255));
        TxtContraseñaCrear.setBorder(null);

        BtnCrearUsuario.setBackground(new java.awt.Color(51, 51, 51));
        BtnCrearUsuario.setForeground(new java.awt.Color(255, 255, 255));
        BtnCrearUsuario.setText("Crear");
        BtnCrearUsuario.setBorder(null);
        BtnCrearUsuario.setPreferredSize(new java.awt.Dimension(75, 25));
        BtnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearUsuarioActionPerformed(evt);
            }
        });

        LblCrearUsuario.setForeground(new java.awt.Color(255, 255, 255));
        LblCrearUsuario.setText("Crear nuevo usuario");

        ComboRol.setBackground(new java.awt.Color(51, 51, 51));
        ComboRol.setForeground(new java.awt.Color(255, 255, 255));
        ComboRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vendedor", "Administrador" }));
        ComboRol.setToolTipText("");
        ComboRol.setBorder(null);
        ComboRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboRolActionPerformed(evt);
            }
        });

        LblTxtCrearUsuario.setForeground(new java.awt.Color(204, 204, 204));
        LblTxtCrearUsuario.setText("Usuario");

        LblTxtCrearContraseña.setForeground(new java.awt.Color(204, 204, 204));
        LblTxtCrearContraseña.setText("Contraseña");

        LblSeleccionarRol.setForeground(new java.awt.Color(204, 204, 204));
        LblSeleccionarRol.setText("Rol");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LblSeleccionarRol, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblTxtCrearContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblTxtCrearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtUsuarioCrear)
                    .addComponent(TxtContraseñaCrear)
                    .addComponent(LblCrearUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboRol, 0, 156, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LblCrearUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtUsuarioCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblTxtCrearUsuario))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtContraseñaCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblTxtCrearContraseña))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblSeleccionarRol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(BtnCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(33, 33, 33));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 33, 33)));

        TxtContraseñaEditar.setBackground(new java.awt.Color(51, 51, 51));
        TxtContraseñaEditar.setForeground(new java.awt.Color(255, 255, 255));
        TxtContraseñaEditar.setBorder(null);

        LblEditarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        LblEditarUsuario.setText("Editar usuario");

        ComboUsuarioaEditar.setBackground(new java.awt.Color(51, 51, 51));
        ComboUsuarioaEditar.setForeground(new java.awt.Color(255, 255, 255));
        ComboUsuarioaEditar.setBorder(null);
        ComboUsuarioaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboUsuarioaEditarActionPerformed(evt);
            }
        });

        LblUsuarioTextFieldEditar.setForeground(new java.awt.Color(204, 204, 204));
        LblUsuarioTextFieldEditar.setText("Usuario");

        LblContraseñaEditar.setForeground(new java.awt.Color(204, 204, 204));
        LblContraseñaEditar.setText("Contraseña Anterior");

        LblEditarCombo.setForeground(new java.awt.Color(204, 204, 204));
        LblEditarCombo.setText("Rol editar");

        ComboRolEditar.setBackground(new java.awt.Color(51, 51, 51));
        ComboRolEditar.setForeground(new java.awt.Color(255, 255, 255));
        ComboRolEditar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vendedor", "Administrador" }));
        ComboRolEditar.setToolTipText("");
        ComboRolEditar.setBorder(null);
        ComboRolEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboRolEditarActionPerformed(evt);
            }
        });

        BtnEditarUsuario.setBackground(new java.awt.Color(51, 51, 51));
        BtnEditarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        BtnEditarUsuario.setText("Editar");
        BtnEditarUsuario.setBorder(null);
        BtnEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarUsuarioActionPerformed(evt);
            }
        });

        LblContraseñaEditar1.setForeground(new java.awt.Color(204, 204, 204));
        LblContraseñaEditar1.setText("Contraseña");

        TxtContraseñaAnterior.setBackground(new java.awt.Color(51, 51, 51));
        TxtContraseñaAnterior.setForeground(new java.awt.Color(255, 255, 255));
        TxtContraseñaAnterior.setBorder(null);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblContraseñaEditar)
                    .addComponent(LblEditarCombo)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(LblUsuarioTextFieldEditar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LblContraseñaEditar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LblEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtContraseñaEditar)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ComboUsuarioaEditar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ComboRolEditar, 0, 156, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(TxtContraseñaAnterior))
                        .addGap(46, 46, 46))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(LblEditarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LblUsuarioTextFieldEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LblContraseñaEditar1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ComboUsuarioaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtContraseñaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblEditarCombo)
                    .addComponent(ComboRolEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblContraseñaEditar)
                    .addComponent(TxtContraseñaAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(BtnEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelTipoCesion, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1057, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(293, 293, 293))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(LabelTipoCesion, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(290, 290, 290))
        );

        JMenuPrincipal.setText("Panel de Opciones");

        MitmVenta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MitmVenta.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        MitmVenta.setText("Venta");
        MitmVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        MitmVenta.setDoubleBuffered(true);
        MitmVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MitmVentaActionPerformed(evt);
            }
        });
        JMenuPrincipal.add(MitmVenta);

        MimtStock.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MimtStock.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        MimtStock.setText("Stock");
        MimtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MimtStockActionPerformed(evt);
            }
        });
        JMenuPrincipal.add(MimtStock);

        MitmCesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MitmCesion.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        MitmCesion.setText("Sesion");
        MitmCesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MitmCesionActionPerformed(evt);
            }
        });
        JMenuPrincipal.add(MitmCesion);

        MitmDevolucion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MitmDevolucion.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        MitmDevolucion.setText("Devolucion");
        JMenuPrincipal.add(MitmDevolucion);

        MitmConsultas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MitmConsultas.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        MitmConsultas.setText("Consultas");
        MitmConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MitmConsultasActionPerformed(evt);
            }
        });
        JMenuPrincipal.add(MitmConsultas);

        MitmSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        MitmSalir.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        MitmSalir.setText("Salir");
        JMenuPrincipal.add(MitmSalir);

        jMenuBar1.add(JMenuPrincipal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MitmVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MitmVentaActionPerformed
        Venta V;
        try {
            V = new Venta();
            V.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al abrir ventas" + e.getMessage());
        }

    }//GEN-LAST:event_MitmVentaActionPerformed

    private void MitmConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MitmConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MitmConsultasActionPerformed

    private void MimtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MimtStockActionPerformed
        Stock S1;
        try {
            S1 = new Stock();
            S1.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al abrir Stock" + ex.getMessage());
            System.out.println(ex.getMessage());
            System.out.println(Arrays.toString(ex.getStackTrace()));
        }

    }//GEN-LAST:event_MimtStockActionPerformed

    private void MitmCesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MitmCesionActionPerformed
        MenuIngreso mi;
        try {
            mi = new MenuIngreso();
            mi.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al abrir menu de cesion " + e.getMessage());
        }
    }//GEN-LAST:event_MitmCesionActionPerformed

    private void TxtUsuarioCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuarioCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuarioCrearActionPerformed
    // traer usuario contraseña y rol 
    private void BtnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearUsuarioActionPerformed
        Usuario nuevoUsuario = new Usuario();
        nuevoUsuario.setName(TxtUsuarioCrear.getText());
        nuevoUsuario.setPassword(TxtContraseñaCrear.getText());
        nuevoUsuario.setAlta(false);
        try {
            nuevoUsuario.setRol(rs.BuscarRol((String) ComboRol.getSelectedItem()));
        } catch (Exception ex) {
            Logger.getLogger(MenuInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        us.crearUsuario(nuevoUsuario);
        try {
            nuevoUsuario = us.BuscarUsuarioPorNombreContraseña(TxtUsuarioCrear.getText(), TxtContraseñaCrear.getText());
        } catch (Exception ex) {
            Logger.getLogger(MenuInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            rs.AgregarUsuarioAdministradorList(nuevoUsuario);
        } catch (Exception ex) {
            Logger.getLogger(MenuInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnCrearUsuarioActionPerformed
    // traer usuario y contraseña nuevo,  y comprobar que sepa la contraseña
    private void BtnEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarUsuarioActionPerformed
         
        Usuario usuarioAEditar = new Usuario();
        
        String mensaje ="";
        
        try {
            mensaje = us.ValidarUsuario((String) ComboUsuarioaEditar.getSelectedItem(),TxtContraseñaAnterior.getText() );
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        if (mensaje.equals( "Entrando 4l $istema")) {
            boolean rolModificado = false;
            usuarioAEditar = us.dao.buscarPorNombreContraseña((String) ComboUsuarioaEditar.getSelectedItem(),TxtContraseñaAnterior.getText() );
            usuarioAEditar.setPassword(TxtContraseñaEditar.getText());
            if (!usuarioAEditar.getRol().getNombre().equals((String) ComboRolEditar.getSelectedItem())) {
                  try {
                usuarioAEditar.setRol(rs.BuscarRol((String) ComboRolEditar.getSelectedItem()));
                rolModificado = true;
            } catch (Exception ex) {
                Logger.getLogger(MenuInicio.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            us.editarUsuario(usuarioAEditar);
            // actulizamos la lista de usuarios administrdore y vendedores
            if (rolModificado) {
                if (usuarioAEditar.getRol().getNombre().equals("Administrador")) {
                    try {
                        rs.AgregarUsuarioAdministradorList(usuarioAEditar);
                    } catch (Exception ex) {
                        Logger.getLogger(MenuInicio.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    rs.EliminarUsuarioVendedorList(usuarioAEditar);
                }else{
                    try {
                        rs.AgregarUsuarioVendedorList(usuarioAEditar);
                    } catch (Exception ex) {
                        Logger.getLogger(MenuInicio.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    rs.EliminarUsuarioAdministradorList(usuarioAEditar);
                } 
            }
        } else {
            JOptionPane.showMessageDialog(null, mensaje);
        }
    }//GEN-LAST:event_BtnEditarUsuarioActionPerformed

    private void ComboUsuarioaEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboUsuarioaEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboUsuarioaEditarActionPerformed

    private void ComboRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboRolActionPerformed

    private void ComboRolEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboRolEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboRolEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    private String disposemessange() {
        Usuario u = us.buscarUsuarioActivo();
        String var = "";
        try {
            var = "El usuario activo es : " + u.getName();
        } catch (Exception e) {
            JOptionPane.showInternalMessageDialog(null, "Error : " + e.getMessage());
        }

        return var;
    }

    private void FillComboBox(JComboBox<String> Combo, List<String> contenido) {
        for (String usuario : contenido) {
            Combo.addItem(usuario);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCrearUsuario;
    private javax.swing.JButton BtnEditarUsuario;
    private javax.swing.JComboBox<String> ComboRol;
    private javax.swing.JComboBox<String> ComboRolEditar;
    private javax.swing.JComboBox<String> ComboUsuarioaEditar;
    private javax.swing.JMenu JMenuPrincipal;
    private javax.swing.JLabel LabelTipoCesion;
    private javax.swing.JLabel LblContraseñaEditar;
    private javax.swing.JLabel LblContraseñaEditar1;
    private javax.swing.JLabel LblCrearUsuario;
    private javax.swing.JLabel LblEditarCombo;
    private javax.swing.JLabel LblEditarUsuario;
    private javax.swing.JLabel LblSeleccionarRol;
    private javax.swing.JLabel LblTxtCrearContraseña;
    private javax.swing.JLabel LblTxtCrearUsuario;
    private javax.swing.JLabel LblUsuarioTextFieldEditar;
    private javax.swing.JMenuItem MimtStock;
    private javax.swing.JMenuItem MitmCesion;
    private javax.swing.JMenuItem MitmConsultas;
    private javax.swing.JMenuItem MitmDevolucion;
    private javax.swing.JMenuItem MitmSalir;
    private javax.swing.JMenuItem MitmVenta;
    private javax.swing.JTextField TxtContraseñaAnterior;
    private javax.swing.JTextField TxtContraseñaCrear;
    private javax.swing.JTextField TxtContraseñaEditar;
    private javax.swing.JTextField TxtUsuarioCrear;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
