/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Servicios.rolServicio;
import Servicios.usuarioService;
import entidades.Rol;
import entidades.Usuario;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JTextField;

/**
 *
 * @author agust
 */
public class MenuIngreso extends javax.swing.JFrame {
    
    usuarioService us = new usuarioService();
    rolServicio rs = new rolServicio();

    /**
     * Creates new form menu_F
     *
     * @throws java.lang.Exception
     */
    public MenuIngreso() throws Exception {
        boolean existeAdmin = us.existeUsuarioAdmin();
        try {
            Usuario u = us.buscarUsuarioActivo();
            if (u != null) {
                us.desactivarUsuario(u);
            }
            
        } catch (Exception e) {
            e.getMessage();
        }
        if (existeAdmin == false) {
            JOptionPane.showMessageDialog(rootPane, "Creando Usuario Administrador Inicial ");
            // Crear nuevo usuario administrador
            Usuario admin = new Usuario();
            admin.setName("admin");
            admin.setPassword("admin");
            admin.setAlta(true);
            Rol rolAdmin = new Rol();
            rolAdmin.setNombre("Administrador");
            rs.crearRol(rolAdmin);
            admin.setRol(rs.BuscarAdminRol());
            us.crearUsuario(admin);
            admin = us.BuscarUsuarioInicial();
            rs.AgregarUsuarioAdministradorList(admin);
            JOptionPane.showMessageDialog(null, "El usuario : admin, fue creado exitosamente, su contraseña es : admin");
        }
        initComponents();
        addPlaceHolderStyle(txtUsuario);
        addPlaceHolderStyle(txtPassword);
            txtUsuario.setText("Usuario");
            txtPassword.setText("Contraseña");
            txtPassword.setEchoChar('\u0000');
            
    }
    
    public void addPlaceHolderStyle(JTextField textfield) {
        Font font = textfield.getFont();
        textfield.setFont(font);
        textfield.setForeground(Color.gray);
        
    }
    
    public void removePlaceHolderStyle(JTextField textfield) {
        // adaptar valores a estilo actual 
        Font font = textfield.getFont();
        font = font.deriveFont(Font.PLAIN);
        textfield.setFont(font);
        textfield.setForeground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        LblBienvenido = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);
        setIconImages(null);

        jPanel1.setBackground(new java.awt.Color(33, 33, 33));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createTitledBorder("")));
        jPanel1.setPreferredSize(new java.awt.Dimension(425, 334));
        jPanel1.setLayout(null);

        LblBienvenido.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        LblBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        LblBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblBienvenido.setText("Login");
        LblBienvenido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(LblBienvenido);
        LblBienvenido.setBounds(10, 40, 370, 65);

        btnAceptar.setBackground(new java.awt.Color(153, 255, 153));
        btnAceptar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAceptar.setText("Entrar");
        btnAceptar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar);
        btnAceptar.setBounds(140, 310, 110, 30);

        txtUsuario.setBackground(new java.awt.Color(51, 51, 51));
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setBorder(null);
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsuario);
        txtUsuario.setBounds(90, 150, 210, 30);

        txtPassword.setBackground(new java.awt.Color(51, 51, 51));
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setText("Contraseña");
        txtPassword.setBorder(null);
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(txtPassword);
        txtPassword.setBounds(90, 210, 210, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        
        String nombre = txtUsuario.getText();
        char[] password = txtPassword.getPassword();
        String concatpas = "";
        txtPassword.setText("");
        txtUsuario.setText("");
        String mensaje;
        for (char c : password) {
            concatpas += c;
        }
        try {
            mensaje = us.ValidarUsuario(nombre, concatpas);
            try {
                if (mensaje.equalsIgnoreCase("Entrando 4l $istema")) {
                    us.activarUsuario(nombre, concatpas);
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
            if (mensaje.equalsIgnoreCase("Entrando 4l $istema")) {
                try {
                    JOptionPane.showMessageDialog(null, "Entrando al Programa");
                    mensaje = us.validarRol(nombre, concatpas);
                    
                    if (mensaje.equalsIgnoreCase("Permisos4dministrador")) {
                        //llamar interfaz administrador
                        MenuInicio adminMenu = new MenuInicio();
                        // Cierra el menú de inicio de sesión actual
                        adminMenu.setVisible(true);

                        // cerrar panel ;de log in 
                    }
                    if (mensaje.equalsIgnoreCase("Permisos5imples")) {
                        //llamar interfaz vendedor 
                        // cerrar panel de log in 
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error en la line 198 : " + e.getMessage());
                }
            }
        } catch (Exception ex) {
            /*Logger.getLogger(MenuIngreso.class.getName()).log(Level.SEVERE, null, ex);*/
            JOptionPane.showMessageDialog(null, "Error en la line 206 : " + ex.getMessage());
            ex.printStackTrace();
        }
        

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        if (txtUsuario.getText().equals("Usuario")) {
            txtUsuario.setText("");
            txtUsuario.requestFocus();
            removePlaceHolderStyle(txtUsuario);
        }
           
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        
            txtPassword.setText("");
            txtPassword.requestFocus();
            removePlaceHolderStyle(txtPassword);
            txtPassword.setEchoChar('\u2022');
      
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
      
        if (txtUsuario.getText().equalsIgnoreCase("")) {
           addPlaceHolderStyle(txtUsuario);
            txtUsuario.setText("Usuario");
        }
       
        
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
       
            addPlaceHolderStyle(txtPassword);
            txtPassword.setText("Contraseña");
            txtPassword.setEchoChar('\u0000');
            
       
    }//GEN-LAST:event_txtPasswordFocusLost
    
    private void verificarUsuarioAdmin() throws Exception {
        boolean existeAdmin = us.existeUsuarioAdmin();
        
        if (existeAdmin = false) {
            // Crear nuevo usuario administrador
            Usuario admin = new Usuario();
            admin.setName("admin");
            admin.setPassword("Administrador");
            admin.setAlta(true);
            
            Rol rolAdmin = new Rol();
            rolAdmin.setNombre("Administrador");
            
            admin.setRol(rolAdmin);

            // revisar servicios  hacer test
            rs.crearRol(rolAdmin);
            rolAdmin = rs.BuscarAdminRol();
            us.crearUsuario(admin);
            
            admin = us.BuscarUsuarioInicial();
            
            rolAdmin = rs.BuscarAdminRol();
            rolAdmin.listaUsuarios.add(admin);
            admin.setRol(rolAdmin);
            admin.setRol(rolAdmin);
            
            rs.editarRol(rolAdmin);
            
            us.editarUsuario(admin);
            
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblBienvenido;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
