/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Servicios.rolServicio;
import Servicios.usuarioService;
import entidades.Rol;
import entidades.Usuario;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JTextField;

/**
 *
 * @author agust
 */
public class MenuIngreso extends javax.swing.JFrame {
    
    usuarioService us = new usuarioService();
    rolServicio rs = new rolServicio();

    /**
     * Creates new form menu_F
     *
     * @throws java.lang.Exception
     */
    public MenuIngreso() throws Exception {
        primerInicio();
        try {
            Usuario u = us.buscarUsuarioActivo();
            if (u != null) {
                us.desactivarUsuario(u);
            }
        } catch (Exception e) {
            e.getMessage();
        }

        initComponents();
        jPanel1.requestFocus();
        addPlaceHolderStyle(txtUsuario);
        addPlaceHolderStyle(txtPassword);
        txtUsuario.setText("Usuario");
        txtPassword.setText("Contraseña");
        txtPassword.setEchoChar('\u0000');
   
    }

    public void addPlaceHolderStyle(JTextField textfield) {
        Font font = textfield.getFont();
        textfield.setFont(font);
        textfield.setForeground(Color.gray);

    }

    public void removePlaceHolderStyle(JTextField textfield) {
        // adaptar valores a estilo actual 
        Font font = textfield.getFont();
        font = font.deriveFont(Font.PLAIN);
        textfield.setFont(font);
        textfield.setForeground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JButton btnAceptar2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        LblBienvenido = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        javax.swing.JButton btnAceptar = new javax.swing.JButton();

        btnAceptar2.setBackground(new java.awt.Color(153, 255, 153));
        btnAceptar2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAceptar2.setText("Entrar");
        btnAceptar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnAceptar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(33, 33, 33));
        setFocusCycleRoot(false);
        setIconImages(null);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(33, 33, 33));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createTitledBorder("")));
        jPanel1.setPreferredSize(new java.awt.Dimension(425, 334));
        jPanel1.setLayout(null);

        LblBienvenido.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        LblBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        LblBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblBienvenido.setText("Login");
        LblBienvenido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(LblBienvenido);
        LblBienvenido.setBounds(0, 40, 370, 65);

        txtUsuario.setBackground(new java.awt.Color(51, 51, 51));
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setBorder(null);
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsuario);
        txtUsuario.setBounds(90, 150, 210, 30);

        txtPassword.setBackground(new java.awt.Color(51, 51, 51));
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setText("Contraseña");
        txtPassword.setBorder(null);
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(txtPassword);
        txtPassword.setBounds(90, 210, 210, 30);

        btnAceptar.setBackground(new java.awt.Color(51, 51, 51));
        btnAceptar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Entrar");
        btnAceptar.setBorder(null);
        jPanel1.add(btnAceptar);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar);
        btnAceptar.setBounds(160, 270, 60, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        if (txtUsuario.getText().equals("Usuario")) {
            txtUsuario.setText("");
            txtUsuario.requestFocus();
            removePlaceHolderStyle(txtUsuario);
        }

    }//GEN-LAST:event_txtUsuarioFocusGained

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained

        txtPassword.setText("");
        txtPassword.requestFocus();
        removePlaceHolderStyle(txtPassword);
        txtPassword.setEchoChar('\u2022');

    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost

        if (txtUsuario.getText().equalsIgnoreCase("")) {
            addPlaceHolderStyle(txtUsuario);
            txtUsuario.setText("Usuario");
        }


    }//GEN-LAST:event_txtUsuarioFocusLost

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        String concatpass = concatenarPassword(txtPassword.getPassword());

        if (concatpass.equals("") || concatpass.equals("Contraseña")) {
            addPlaceHolderStyle(txtPassword);
            txtPassword.setText("Contraseña");
            txtPassword.setEchoChar('\u0000');
        }


    }//GEN-LAST:event_txtPasswordFocusLost

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
     
        String nombre = txtUsuario.getText();
        String concatpas = concatenarPassword(txtPassword.getPassword());
        String mensaje;
        try {
            mensaje = us.ValidarUsuario(nombre, concatpas);
            try {
                if (mensaje.equalsIgnoreCase("Entrando 4l $istema")) {
                    us.activarUsuario(nombre, concatpas);
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
            if (mensaje.equalsIgnoreCase("Entrando 4l $istema")) {
                try {
                    
                    mensaje = us.validarRol(nombre, concatpas);

                    if (mensaje.equalsIgnoreCase("Permisos4dministrador")) {
                        //llamar interfaz administrador
                        UsuarioAdmin adminMenu = new UsuarioAdmin();
                        adminMenu.setVisible(true);
                        adminMenu.setLocationRelativeTo(null);
                         // Cierra el menú de inicio de sesión actual
                        // cerrar panel ;de log in 
                    }
                    if (mensaje.equalsIgnoreCase("Permisos5imples")) {
                        ventasVendedor vV = new ventasVendedor();
                        vV.setVisible(true);
                        vV.setLocationRelativeTo(null);
                        // cerrar panel de log in 
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error en la line 198 : " + e.getMessage());
                }
            }
        } catch (Exception ex) {
            /*Logger.getLogger(MenuIngreso.class.getName()).log(Level.SEVERE, null, ex);*/
            JOptionPane.showMessageDialog(null, "Error en la line 206 : " + ex.getMessage());
            ex.printStackTrace();
        }


    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnAceptar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar2ActionPerformed

    }//GEN-LAST:event_btnAceptar2ActionPerformed

   
    

    private String concatenarPassword(char[] pass) {
        String concatpass = "";
        for (char c : pass) {
            concatpass = concatpass + c;
        }
        return concatpass;
    }

    private void primerInicio() throws Exception {
        boolean existeAdmin = us.existeUsuarioAdmin();
        if (existeAdmin == false) {
            JOptionPane.showMessageDialog(rootPane, "Creando Usuario Administrador Inicial ");
            // Crear nuevo usuario administrador
            Usuario admin = new Usuario();
            admin.setName("admin");
            admin.setPassword("admin");
            admin.setAlta(true);
            //creamos rol administrador
            Rol rolAdmin = rs.crearRol("Administrador");

            //crear rol vendedor 
            Rol rolVendedor =  rs.crearRol("Vendedor");
            //asignamos rol de administrador a primer usuario y despues se persiste
            admin.setRol(rs.BuscarAdminRol());
            us.crearUsuario(admin);
            // buscamos el primer usuario para añadirlo a la lista de administradores 
            admin = us.BuscarUsuarioInicial();
            rs.AgregarUsuarioAdministradorList(admin);
            JOptionPane.showMessageDialog(null, "El usuario : admin, fue creado exitosamente, su contraseña es : admin");
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblBienvenido;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
