/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Entidades.Product;
import ServicioIU.InterfaceService;
import Servicios.ProductService;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author agust
 */
public class stockEditarVendedor extends javax.swing.JFrame {

    String selectionMarca;
    String selectionCategoria;
    DefaultTableModel model;
    ProductService Ps;
    InterfaceService Ss;
    private List<Product> products2;
    //checkear que hace bottongroup
    ButtonGroup groupButtons;

    /**
     * Creates new form stockEditarVentas
     */
    public stockEditarVendedor() throws Exception {
             this.Ss = new InterfaceService();
        this.Ps = new ProductService(); 
        this.selectionCategoria="";
        this.selectionMarca="";
        products2 = Ps.Dao.listarTodos();        
        this.groupButtons = new ButtonGroup();
        initComponents();
        ComboMarca.addItem("");
        this.model = Ss.Display((DefaultTableModel) TableVenta.getModel(), products2);
        // Agregar eventos de cambio de valor a las celdas
        model.addTableModelListener((TableModelEvent e) -> {
            if (e.getType() == TableModelEvent.UPDATE) {
                int row = e.getFirstRow();
                int column = e.getColumn();
                // Verificar si se modificó alguna de las columnas de interés
                if (column == 4 || column == 5 || column == 8) {
                    // agregar que interprete a cualquier valor nulo en la cas illa como = a 0 dentro de calculatePrice
                    calculatePrice(row, model);
                }
            }     
            
        });
           FillComboBox(ComboCategoria,(List<String>) Ps.Dao.TraerTodasCategorias());
            FillComboBox(ComboMarca,(List<String>) Ps.Dao.TraerTodasMarcas());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BtnAceptar = new javax.swing.JButton();
        ComboCategoria = new javax.swing.JComboBox<>();
        LabelCategoria = new javax.swing.JLabel();
        ComboMarca = new javax.swing.JComboBox<>();
        LabelMarca = new javax.swing.JLabel();
        BtnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableVenta = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenuPrincipalVendedor = new javax.swing.JMenu();
        MitmVenta = new javax.swing.JMenuItem();
        MitmAgregarStock = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        MitmDevolucion = new javax.swing.JMenuItem();
        MitmCesion = new javax.swing.JMenuItem();
        MitmSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(33, 33, 33));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);

        jPanel2.setBackground(new java.awt.Color(33, 33, 33));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        BtnAceptar.setBackground(new java.awt.Color(51, 51, 51));
        BtnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAceptar.setText("Hacer Edicion");
        BtnAceptar.setToolTipText("Las celdas seleccionadas al momento de Hacer edicion no se veran afectadas");
        BtnAceptar.setBorder(null);
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });

        ComboCategoria.setBackground(new java.awt.Color(51, 51, 51));
        ComboCategoria.setForeground(new java.awt.Color(255, 255, 255));
        ComboCategoria.setToolTipText("");
        ComboCategoria.setBorder(null);
        ComboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboCategoriaActionPerformed(evt);
            }
        });

        LabelCategoria.setForeground(new java.awt.Color(255, 255, 255));
        LabelCategoria.setText("Seleccione cátegoria buscada: ");

        ComboMarca.setBackground(new java.awt.Color(51, 51, 51));
        ComboMarca.setForeground(new java.awt.Color(255, 255, 255));
        ComboMarca.setBorder(null);
        ComboMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboMarcaActionPerformed(evt);
            }
        });

        LabelMarca.setForeground(new java.awt.Color(255, 255, 255));
        LabelMarca.setText("Seleccione marca buscada: ");

        BtnBuscar.setBackground(new java.awt.Color(51, 51, 51));
        BtnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        BtnBuscar.setText("Buscar");
        BtnBuscar.setBorder(null);
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelCategoria)
                    .addComponent(LabelMarca)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ComboCategoria, 0, 123, Short.MAX_VALUE)
                                .addComponent(ComboMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(BtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(LabelCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelMarca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(BtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setMaximumSize(new java.awt.Dimension(555555555, 555555555));

        TableVenta.setBackground(new java.awt.Color(51, 51, 51));
        TableVenta.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        TableVenta.setForeground(new java.awt.Color(255, 255, 255));
        TableVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Marca", "Categoria", "Precio de compra", "Precio", "Stock", "Alerta stock", "Interes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableVenta.setAutoscrolls(false);
        TableVenta.setCellSelectionEnabled(true);
        TableVenta.setFillsViewportHeight(true);
        TableVenta.setGridColor(new java.awt.Color(0, 0, 0));
        TableVenta.setInheritsPopupMenu(true);
        TableVenta.setMaximumSize(new java.awt.Dimension(2147483647, 555555555));
        TableVenta.setMinimumSize(new java.awt.Dimension(800, 600));
        TableVenta.setName(""); // NOI18N
        TableVenta.setSelectionForeground(new java.awt.Color(255, 255, 255));
        TableVenta.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TableVenta);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1109, Short.MAX_VALUE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(114, 23));

        JMenuPrincipalVendedor.setText("Panel de Opciones");
        JMenuPrincipalVendedor.setMinimumSize(new java.awt.Dimension(120, 22));
        JMenuPrincipalVendedor.setPreferredSize(new java.awt.Dimension(114, 30));
        JMenuPrincipalVendedor.setRolloverEnabled(false);

        MitmVenta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MitmVenta.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        MitmVenta.setText("Venta");
        MitmVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        MitmVenta.setDoubleBuffered(true);
        MitmVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MitmVentaActionPerformed(evt);
            }
        });
        JMenuPrincipalVendedor.add(MitmVenta);

        MitmAgregarStock.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MitmAgregarStock.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        MitmAgregarStock.setText("Agregar Stock");
        MitmAgregarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MitmAgregarStockActionPerformed(evt);
            }
        });
        JMenuPrincipalVendedor.add(MitmAgregarStock);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        jMenuItem1.setText("Editar Stock");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        JMenuPrincipalVendedor.add(jMenuItem1);

        MitmDevolucion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MitmDevolucion.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        MitmDevolucion.setText("Devolucion");
        MitmDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MitmDevolucionActionPerformed(evt);
            }
        });
        JMenuPrincipalVendedor.add(MitmDevolucion);

        MitmCesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MitmCesion.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        MitmCesion.setText("Sesion");
        MitmCesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MitmCesionActionPerformed(evt);
            }
        });
        JMenuPrincipalVendedor.add(MitmCesion);

        MitmSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        MitmSalir.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        MitmSalir.setText("Salir");
        MitmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MitmSalirActionPerformed(evt);
            }
        });
        JMenuPrincipalVendedor.add(MitmSalir);

        jMenuBar1.add(JMenuPrincipalVendedor);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        try {
            //TODO checkear comprobar precios
            TableModel modelbis = this.TableVenta.getModel();
            model = (DefaultTableModel) modelbis;
            products2 = Ss.EditaleData(Ss.comprobarPrecios(model));
            for (Product product : products2) {
                Ps.Dao.editar(product);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Error en btn aceptar linea 281 Stock : " + ex.getMessage());
        }
    }//GEN-LAST:event_BtnAceptarActionPerformed

    private void ComboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCategoriaActionPerformed
        selectionCategoria = (String) ComboCategoria.getSelectedItem();
    }//GEN-LAST:event_ComboCategoriaActionPerformed

    private void ComboMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboMarcaActionPerformed
        selectionMarca = (String) ComboMarca.getSelectedItem();
    }//GEN-LAST:event_ComboMarcaActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        if (!selectionCategoria.equals("")&& selectionMarca.equals("")) {
            try {
                products2= Ps.Dao.buscarPorCategoria(selectionCategoria);
                Ss.Display(model, products2);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error :"+ex.getMessage());
            }
        }
        if (selectionCategoria.equals("")&& !selectionMarca.equals("")) {
            try {
                products2= Ps.Dao.buscarPorMarca(selectionMarca);
                Ss.Display(model, products2);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error :"+ex.getMessage());
            }
            if (!selectionCategoria.equals("")&& !selectionMarca.equals("")){
                try {
                    products2= Ps.Dao.buscarPorCategoriayMarca(selectionCategoria, selectionMarca);
                    Ss.Display(model, products2);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Error :"+ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void MitmVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MitmVentaActionPerformed
        ventasVendedor V;
        try {
            V = new ventasVendedor();
            V.setVisible(true);
            V.setLocationRelativeTo(null);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al abrir ventas" + e.getMessage());
        }
    }//GEN-LAST:event_MitmVentaActionPerformed

    private void MitmAgregarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MitmAgregarStockActionPerformed
        stockAgregarVendedor s1;
        try {
            s1 = new stockAgregarVendedor();
            s1.setVisible(true);
            s1.setLocationRelativeTo(null);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al abrir menu de AgregarStock : " + e.getMessage());
        }
    }//GEN-LAST:event_MitmAgregarStockActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        stockEditarVendedor S1;
        try {
            S1 = new stockEditarVendedor();
            S1.setVisible(true);
            S1.setLocationRelativeTo(null);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al abrir Stock Editar : " + ex.getMessage());

            ex.getStackTrace();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MitmDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MitmDevolucionActionPerformed
        DevolucionesVendedores dv;
        try {
            dv = new DevolucionesVendedores();
            dv.setVisible(true);
            dv.setLocationRelativeTo(null);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al abrir Devoluciones : " + ex.getMessage());
        }

    }//GEN-LAST:event_MitmDevolucionActionPerformed

    private void MitmCesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MitmCesionActionPerformed
        MenuIngreso mi;
        try {
            mi = new MenuIngreso();
            mi.setVisible(true);
            mi.setLocationRelativeTo(null);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al abrir menu de cesion " + e.getMessage());
        }
    }//GEN-LAST:event_MitmCesionActionPerformed

    private void MitmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MitmSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_MitmSalirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JComboBox<String> ComboCategoria;
    private javax.swing.JComboBox<String> ComboMarca;
    private javax.swing.JMenu JMenuPrincipalVendedor;
    private javax.swing.JLabel LabelCategoria;
    private javax.swing.JLabel LabelMarca;
    private javax.swing.JMenuItem MitmAgregarStock;
    private javax.swing.JMenuItem MitmCesion;
    private javax.swing.JMenuItem MitmDevolucion;
    private javax.swing.JMenuItem MitmSalir;
    private javax.swing.JMenuItem MitmVenta;
    private javax.swing.JTable TableVenta;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void FillComboBox(JComboBox<String> Combo,List<String> contenido) {
        
        if (Combo == ComboMarca) {
             
            for (String marca : contenido) {
                Combo.addItem(marca);
            }
        } else {
          
            for (String categoria : contenido) {
                Combo.addItem(categoria);
            }
        }
    }
    
     private void calculatePrice(int row, DefaultTableModel model1) {        
        try {            
            Double precioCompra = (Double) model1.getValueAt(row, 4);
            Double interes = (Double) model1.getValueAt(row, 8);
            Double precio = (Double) model1.getValueAt(row, 5);
            // Verificar si los valores necesarios están presentes y el interés es diferente de cero
            if (precioCompra != 0 && interes != 0 && precio == 0) {
                precio = precioCompra * (interes + 1);
                model.setValueAt(precio, row, 5);                
            }
            if (precioCompra != 0 && precio != 0 && interes == 0) {
                interes = (precio / precioCompra) - 1;
                model.setValueAt(interes, row, 8);                
            }
        } catch (Exception e) {
            System.out.println(e.getCause());
            System.out.println(e.getClass());
            System.out.println(e.toString());
        }
        
    }
     
}
