/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Servicios.rolServicio;
import Servicios.usuarioService;
import entidades.Usuario;
import java.awt.Color;
import java.awt.Font;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author agust
 */
public class UsuarioAdmin extends javax.swing.JFrame {

    usuarioService us = new usuarioService();
    rolServicio rs = new rolServicio();

    /**
     * Creates new form MenuInicio
     */
    public UsuarioAdmin() {
        initComponents();
        FillComboBox(ComboUsuarioaEditar, us.dao.TraerTodosUsuario());
        addPlaceHolderStyle(TxtUsuarioCrear);
        addPlaceHolderStyle(jTextField1);
        addPlaceHolderStyle(TxtContraseñaEditar);
        addPlaceHolderStyle(TxtContraseñaAnterior);
        addPlaceHolderStyle(TxtContraseñaCrear);
        TxtContraseñaCrear.setText("Contraseña del nuevo usuario");
        jTextField1.setText("Nuevo nombre");
        TxtContraseñaEditar.setText("Nueva Contraseña");
        TxtContraseñaAnterior.setText("Contraseña Anterior");
        TxtUsuarioCrear.setText("Nombre del nuevo usuario");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelTipoCesion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        TxtUsuarioCrear = new javax.swing.JTextField();
        TxtContraseñaCrear = new javax.swing.JTextField();
        BtnCrearUsuario = new javax.swing.JButton();
        ComboRol = new javax.swing.JComboBox<>();
        LblCrearUsuario = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        TxtContraseñaEditar = new javax.swing.JTextField();
        LblEditarUsuario = new javax.swing.JLabel();
        ComboUsuarioaEditar = new javax.swing.JComboBox<>();
        ComboRolEditar = new javax.swing.JComboBox<>();
        BtnEditarUsuario = new javax.swing.JButton();
        TxtContraseñaAnterior = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        LabelDarDeBaja = new javax.swing.JLabel();
        ComboUsuarioEliminar = new javax.swing.JComboBox<>();
        BtnEliminar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenuPrincipal = new javax.swing.JMenu();
        MitmVenta = new javax.swing.JMenuItem();
        MimtStock = new javax.swing.JMenuItem();
        MitmEditar = new javax.swing.JMenuItem();
        MitmDevolucion = new javax.swing.JMenuItem();
        jMenuUsuario = new javax.swing.JMenuItem();
        MitmCesion = new javax.swing.JMenuItem();
        MitmSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(getMaximumSize());

        jPanel1.setBackground(new java.awt.Color(33, 33, 33));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setEnabled(false);
        jPanel1.setFocusCycleRoot(true);
        jPanel1.setVerifyInputWhenFocusTarget(false);

        LabelTipoCesion.setBackground(new java.awt.Color(33, 33, 33));
        LabelTipoCesion.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        LabelTipoCesion.setForeground(new java.awt.Color(255, 255, 255));
        LabelTipoCesion.setText(disposemessange());

        jPanel2.setBackground(new java.awt.Color(33, 33, 33));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 33, 33)));

        TxtUsuarioCrear.setBackground(new java.awt.Color(51, 51, 51));
        TxtUsuarioCrear.setForeground(new java.awt.Color(255, 255, 255));
        TxtUsuarioCrear.setBorder(null);
        TxtUsuarioCrear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtUsuarioCrearFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtUsuarioCrearFocusLost(evt);
            }
        });
        TxtUsuarioCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuarioCrearActionPerformed(evt);
            }
        });

        TxtContraseñaCrear.setBackground(new java.awt.Color(51, 51, 51));
        TxtContraseñaCrear.setForeground(new java.awt.Color(255, 255, 255));
        TxtContraseñaCrear.setBorder(null);
        TxtContraseñaCrear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtContraseñaCrearFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtContraseñaCrearFocusLost(evt);
            }
        });
        TxtContraseñaCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtContraseñaCrearActionPerformed(evt);
            }
        });

        BtnCrearUsuario.setBackground(new java.awt.Color(51, 51, 51));
        BtnCrearUsuario.setForeground(new java.awt.Color(255, 255, 255));
        BtnCrearUsuario.setText("Crear");
        BtnCrearUsuario.setBorder(null);
        BtnCrearUsuario.setPreferredSize(new java.awt.Dimension(75, 25));
        BtnCrearUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BtnCrearUsuarioFocusGained(evt);
            }
        });
        BtnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearUsuarioActionPerformed(evt);
            }
        });

        ComboRol.setBackground(new java.awt.Color(51, 51, 51));
        ComboRol.setForeground(new java.awt.Color(255, 255, 255));
        ComboRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vendedor", "Administrador" }));
        ComboRol.setToolTipText("");
        ComboRol.setBorder(null);
        ComboRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboRolActionPerformed(evt);
            }
        });

        LblCrearUsuario.setForeground(new java.awt.Color(255, 255, 255));
        LblCrearUsuario.setText("Crear nuevo usuario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtUsuarioCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TxtContraseñaCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ComboRol, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(BtnCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblCrearUsuario)
                .addGap(26, 26, 26)
                .addComponent(TxtUsuarioCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TxtContraseñaCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ComboRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(BtnCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        jPanel3.setBackground(new java.awt.Color(33, 33, 33));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 33, 33)));

        TxtContraseñaEditar.setBackground(new java.awt.Color(51, 51, 51));
        TxtContraseñaEditar.setForeground(new java.awt.Color(255, 255, 255));
        TxtContraseñaEditar.setActionCommand("<Not Set>");
        TxtContraseñaEditar.setBorder(null);
        TxtContraseñaEditar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtContraseñaEditarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtContraseñaEditarFocusLost(evt);
            }
        });
        TxtContraseñaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtContraseñaEditarActionPerformed(evt);
            }
        });

        LblEditarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        LblEditarUsuario.setText("Editar usuario");

        ComboUsuarioaEditar.setBackground(new java.awt.Color(51, 51, 51));
        ComboUsuarioaEditar.setForeground(new java.awt.Color(255, 255, 255));
        ComboUsuarioaEditar.setBorder(null);
        ComboUsuarioaEditar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ComboUsuarioaEditarFocusGained(evt);
            }
        });
        ComboUsuarioaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboUsuarioaEditarActionPerformed(evt);
            }
        });

        ComboRolEditar.setBackground(new java.awt.Color(51, 51, 51));
        ComboRolEditar.setForeground(new java.awt.Color(255, 255, 255));
        ComboRolEditar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vendedor", "Administrador" }));
        ComboRolEditar.setToolTipText("");
        ComboRolEditar.setBorder(null);
        ComboRolEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboRolEditarActionPerformed(evt);
            }
        });

        BtnEditarUsuario.setBackground(new java.awt.Color(51, 51, 51));
        BtnEditarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        BtnEditarUsuario.setText("Editar");
        BtnEditarUsuario.setBorder(null);
        BtnEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarUsuarioActionPerformed(evt);
            }
        });

        TxtContraseñaAnterior.setBackground(new java.awt.Color(51, 51, 51));
        TxtContraseñaAnterior.setForeground(new java.awt.Color(255, 255, 255));
        TxtContraseñaAnterior.setBorder(null);
        TxtContraseñaAnterior.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtContraseñaAnteriorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtContraseñaAnteriorFocusLost(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(55, 55, 55));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(null);
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboUsuarioaEditar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboRolEditar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(TxtContraseñaAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(BtnEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(TxtContraseñaEditar)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(LblEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(ComboUsuarioaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TxtContraseñaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ComboRolEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(TxtContraseñaAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        jPanel4.setBackground(new java.awt.Color(33, 33, 33));
        jPanel4.setPreferredSize(new java.awt.Dimension(178, 227));

        LabelDarDeBaja.setForeground(new java.awt.Color(255, 255, 255));
        LabelDarDeBaja.setText("Dar de baja usuario");

        ComboUsuarioEliminar.setBackground(new java.awt.Color(51, 51, 51));
        ComboUsuarioEliminar.setForeground(new java.awt.Color(255, 255, 255));
        ComboUsuarioEliminar.setBorder(null);
        ComboUsuarioEliminar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ComboUsuarioEliminarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ComboUsuarioEliminarFocusLost(evt);
            }
        });
        ComboUsuarioEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboUsuarioEliminarActionPerformed(evt);
            }
        });

        BtnEliminar.setBackground(new java.awt.Color(51, 51, 51));
        BtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        BtnEliminar.setText("Eliminar ");
        BtnEliminar.setToolTipText("");
        BtnEliminar.setAutoscrolls(true);
        BtnEliminar.setBorder(null);
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ComboUsuarioEliminar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(LabelDarDeBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelDarDeBaja)
                .addGap(26, 26, 26)
                .addComponent(ComboUsuarioEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(291, 291, 291))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelTipoCesion, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(LabelTipoCesion, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(308, Short.MAX_VALUE))
        );

        JMenuPrincipal.setText("Panel de Opciones");

        MitmVenta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MitmVenta.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        MitmVenta.setText("Venta");
        MitmVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        MitmVenta.setDoubleBuffered(true);
        MitmVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MitmVentaActionPerformed(evt);
            }
        });
        JMenuPrincipal.add(MitmVenta);

        MimtStock.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MimtStock.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        MimtStock.setText("Stock Agrgar");
        MimtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MimtStockActionPerformed(evt);
            }
        });
        JMenuPrincipal.add(MimtStock);

        MitmEditar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MitmEditar.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        MitmEditar.setText("Stock Editar");
        MitmEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MitmEditarActionPerformed(evt);
            }
        });
        JMenuPrincipal.add(MitmEditar);

        MitmDevolucion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MitmDevolucion.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        MitmDevolucion.setText("Devolucion");
        MitmDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MitmDevolucionActionPerformed(evt);
            }
        });
        JMenuPrincipal.add(MitmDevolucion);

        jMenuUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuUsuario.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        jMenuUsuario.setText("Usuarios");
        jMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuarioActionPerformed(evt);
            }
        });
        JMenuPrincipal.add(jMenuUsuario);

        MitmCesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MitmCesion.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        MitmCesion.setText("Cesion");
        MitmCesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MitmCesionActionPerformed(evt);
            }
        });
        JMenuPrincipal.add(MitmCesion);

        MitmSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        MitmSalir.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        MitmSalir.setText("Salir");
        MitmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MitmSalirActionPerformed(evt);
            }
        });
        JMenuPrincipal.add(MitmSalir);

        jMenuBar1.add(JMenuPrincipal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MitmVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MitmVentaActionPerformed
        ventasVendedor V;
        try {
            V = new ventasVendedor();
            V.setExtendedState(JFrame.MAXIMIZED_BOTH);
            V.setVisible(true);
            V.setLocationRelativeTo(null);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al abrir ventas" + e.getMessage());
        }

    }//GEN-LAST:event_MitmVentaActionPerformed

    private void MitmEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MitmEditarActionPerformed
        StockEditarAdminR S1;
        try {
            S1 = new StockEditarAdminR();
            S1.setExtendedState(JFrame.MAXIMIZED_BOTH);
            S1.setVisible(true);
            S1.setLocationRelativeTo(null);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al abrir Stock editar . " + ex.getMessage());
        }
    }//GEN-LAST:event_MitmEditarActionPerformed

    private void MimtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MimtStockActionPerformed
        stockAgregarAdmin s1;
        try {
            s1 = new stockAgregarAdmin();
            s1.setExtendedState(JFrame.MAXIMIZED_BOTH);
            s1.setVisible(true);
            s1.setLocationRelativeTo(null);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al abrir Stock Agregar : " + ex.getMessage());
        }


    }//GEN-LAST:event_MimtStockActionPerformed

    private void MitmCesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MitmCesionActionPerformed
        MenuIngreso mi;
        try {
            mi = new MenuIngreso();
            mi.setVisible(true);
            mi.setLocationRelativeTo(null);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al abrir menu de cesion : " + e.getMessage());
        }
    }//GEN-LAST:event_MitmCesionActionPerformed

    private void TxtUsuarioCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuarioCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuarioCrearActionPerformed
    // traer usuario contraseña y rol 
    private void BtnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearUsuarioActionPerformed
        Usuario nuevoUsuario = new Usuario();
        nuevoUsuario.setName(TxtUsuarioCrear.getText());
        nuevoUsuario.setPassword(TxtContraseñaCrear.getText());
        nuevoUsuario.setAlta(false);
        try {
            int id = ComboRol.getSelectedIndex() + 1;
            nuevoUsuario.setRol(rs.buscarPorId(id));
        } catch (Exception ex) {
            Logger.getLogger(UsuarioAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        us.crearUsuario(nuevoUsuario);
        try {
            nuevoUsuario = us.BuscarUsuarioPorNombreContraseña(TxtUsuarioCrear.getText(), TxtContraseñaCrear.getText());
        } catch (Exception ex) {
            Logger.getLogger(UsuarioAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            rs.AgregarUsuarioAdministradorList(nuevoUsuario);
        } catch (Exception ex) {
            Logger.getLogger(UsuarioAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnCrearUsuarioActionPerformed
    // traer usuario y contraseña nuevo,  y comprobar que sepa la contraseña
    private void BtnEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarUsuarioActionPerformed

        Usuario usuarioAEditar = new Usuario();

        String mensaje = "";

        try {
            mensaje = us.ValidarUsuario((String) ComboUsuarioaEditar.getSelectedItem(), TxtContraseñaAnterior.getText());
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        if (mensaje.equals("Entrando 4l $istema")) {
            boolean rolModificado = false;
            usuarioAEditar = us.dao.buscarPorNombreContraseña((String) ComboUsuarioaEditar.getSelectedItem(), TxtContraseñaAnterior.getText());
            usuarioAEditar.setPassword(TxtContraseñaEditar.getText());
            if (!usuarioAEditar.getRol().getNombre().equals((String) ComboRolEditar.getSelectedItem())) {
                try {
                    usuarioAEditar.setRol(rs.buscarPorId(ComboRolEditar.getSelectedIndex() + 1));
                    rolModificado = true;
                } catch (Exception ex) {
                    Logger.getLogger(UsuarioAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            us.editarUsuario(usuarioAEditar);
            // actulizamos la lista de usuarios administrdore y vendedores
            if (rolModificado) {
                if (usuarioAEditar.getRol().getNombre().equals("Administrador")) {
                    try {
                        rs.AgregarUsuarioAdministradorList(usuarioAEditar);
                    } catch (Exception ex) {
                        Logger.getLogger(UsuarioAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    rs.EliminarUsuarioVendedorList(usuarioAEditar);
                } else {
                    try {
                        rs.AgregarUsuarioVendedorList(usuarioAEditar);
                    } catch (Exception ex) {
                        Logger.getLogger(UsuarioAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    rs.EliminarUsuarioAdministradorList(usuarioAEditar);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, mensaje);
        }
    }//GEN-LAST:event_BtnEditarUsuarioActionPerformed

    private void ComboUsuarioaEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboUsuarioaEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboUsuarioaEditarActionPerformed

    private void ComboRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboRolActionPerformed

    private void ComboRolEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboRolEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboRolEditarActionPerformed

    private void TxtContraseñaEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtContraseñaEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtContraseñaEditarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        if (jTextField1.getText().equals("Nuevo nombre")) {
            jTextField1.setText("");
            jTextField1.requestFocus();
            removePlaceHolderStyle(jTextField1);
        }
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost

        if (jTextField1.getText().equalsIgnoreCase("")) {
            addPlaceHolderStyle(jTextField1);
            jTextField1.setText("Nuevo nombre");
        }
    }//GEN-LAST:event_jTextField1FocusLost

    private void TxtContraseñaEditarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtContraseñaEditarFocusGained
        if (TxtContraseñaEditar.getText().equals("Nueva Contraseña")) {
            TxtContraseñaEditar.setText("");
            TxtContraseñaEditar.requestFocus();
            removePlaceHolderStyle(TxtContraseñaEditar);
        }
    }//GEN-LAST:event_TxtContraseñaEditarFocusGained

    private void TxtContraseñaEditarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtContraseñaEditarFocusLost
        if (TxtContraseñaEditar.getText().equalsIgnoreCase("")) {
            addPlaceHolderStyle(TxtContraseñaEditar);
            TxtContraseñaEditar.setText("Nueva Contraseña");
        }
    }//GEN-LAST:event_TxtContraseñaEditarFocusLost

    private void TxtContraseñaAnteriorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtContraseñaAnteriorFocusGained
        if (TxtContraseñaAnterior.getText().equals("Contraseña Anterior")) {
            TxtContraseñaAnterior.setText("");
            TxtContraseñaAnterior.requestFocus();
            removePlaceHolderStyle(TxtContraseñaAnterior);
        }
    }//GEN-LAST:event_TxtContraseñaAnteriorFocusGained
    private void TxtContraseñaAnteriorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtContraseñaAnteriorFocusLost
        if (TxtContraseñaAnterior.getText().equalsIgnoreCase("")) {
            addPlaceHolderStyle(TxtContraseñaAnterior);
            TxtContraseñaAnterior.setText("Contraseña Anterior");
        }
    }//GEN-LAST:event_TxtContraseñaAnteriorFocusLost

    private void TxtUsuarioCrearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtUsuarioCrearFocusGained
        if (TxtUsuarioCrear.getText().equals("Nombre del nuevo usuario")) {
            TxtUsuarioCrear.setText("");
            TxtUsuarioCrear.requestFocus();
            removePlaceHolderStyle(TxtUsuarioCrear);
        }
    }//GEN-LAST:event_TxtUsuarioCrearFocusGained

    private void TxtUsuarioCrearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtUsuarioCrearFocusLost
        if (TxtUsuarioCrear.getText().equalsIgnoreCase("")) {
            addPlaceHolderStyle(TxtUsuarioCrear);
            TxtUsuarioCrear.setText("Nombre del nuevo usuario");
        }
    }//GEN-LAST:event_TxtUsuarioCrearFocusLost

    private void TxtContraseñaCrearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtContraseñaCrearFocusGained
        if (TxtContraseñaCrear.getText().equals("Contraseña del nuevo usuario")) {
            TxtContraseñaCrear.setText("");
            TxtContraseñaCrear.requestFocus();
            removePlaceHolderStyle(TxtContraseñaCrear);
        }
    }//GEN-LAST:event_TxtContraseñaCrearFocusGained

    private void TxtContraseñaCrearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtContraseñaCrearFocusLost
        if (TxtContraseñaCrear.getText().equalsIgnoreCase("")) {
            addPlaceHolderStyle(TxtContraseñaCrear);
            TxtContraseñaCrear.setText("Contraseña del nuevo usuario");
        }
    }//GEN-LAST:event_TxtContraseñaCrearFocusLost

    private void BtnCrearUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BtnCrearUsuarioFocusGained


    }//GEN-LAST:event_BtnCrearUsuarioFocusGained

    private void ComboUsuarioEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboUsuarioEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboUsuarioEliminarActionPerformed

    private void ComboUsuarioEliminarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ComboUsuarioEliminarFocusGained
        FillComboBox(ComboUsuarioEliminar, us.dao.TraerTodosUsuario());
    }//GEN-LAST:event_ComboUsuarioEliminarFocusGained

    private void ComboUsuarioEliminarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ComboUsuarioEliminarFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboUsuarioEliminarFocusLost

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        int IdRef = ComboUsuarioEliminar.getSelectedIndex() + 1;
        Usuario u = new Usuario();
        try {
            //el index inicia en 0
            u = us.BuscarUsuarioid(IdRef);
        } catch (Exception ex) {
            System.out.println("Error btn eliminar : " + ex.getMessage());
        }
        try {
            if (us.AdminControl(ComboUsuarioEliminar.getSelectedIndex() + 1)) {
                us.dao.eliminar(u);
            }

        } catch (Exception ex) {
            System.out.println("Error AdminControl : " + ex.getMessage());
        }

    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void TxtContraseñaCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtContraseñaCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtContraseñaCrearActionPerformed

    private void ComboUsuarioaEditarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ComboUsuarioaEditarFocusGained
        FillComboBox(ComboUsuarioaEditar, us.dao.TraerTodosUsuario());
    }//GEN-LAST:event_ComboUsuarioaEditarFocusGained

    private void MitmDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MitmDevolucionActionPerformed
        try {
            DevolucionesAdmin d = new DevolucionesAdmin();
            d.setExtendedState(JFrame.MAXIMIZED_BOTH);
            d.setVisible(true);
            d.setLocationRelativeTo(null);
            this.dispose();
        } catch (Exception ex) {
               JOptionPane.showMessageDialog(null, "Error al abrir devolucion : " + ex.getMessage());
        }

    }//GEN-LAST:event_MitmDevolucionActionPerformed

    private void jMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuarioActionPerformed
        UsuarioAdmin mi = new UsuarioAdmin();
        mi.setExtendedState(JFrame.MAXIMIZED_BOTH);
        mi.setVisible(true);
        mi.setLocationRelativeTo(null);
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuUsuarioActionPerformed

    private void MitmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MitmSalirActionPerformed
       this.dispose();
    }//GEN-LAST:event_MitmSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    private String disposemessange() {
        Usuario u = us.buscarUsuarioActivo();
        String var = "";
        try {
            var = "El usuario activo es : " + u.getName();
        } catch (Exception e) {
            JOptionPane.showInternalMessageDialog(null, "Error : " + e.getMessage());
        }

        return var;
    }

    private void FillComboBox(JComboBox<String> Combo, List<String> contenido) {
        Combo.removeAllItems();
        for (String usuario : contenido) {
            Combo.addItem(usuario);
        }
    }

    public void addPlaceHolderStyle(JTextField textfield) {
        Font font = textfield.getFont();
        textfield.setFont(font);
        textfield.setForeground(Color.gray);

    }

    public void removePlaceHolderStyle(JTextField textfield) {
        // adaptar valores a estilo actual 
        Font font = textfield.getFont();
        font = font.deriveFont(Font.PLAIN);
        textfield.setFont(font);
        textfield.setForeground(Color.WHITE);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCrearUsuario;
    private javax.swing.JButton BtnEditarUsuario;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JComboBox<String> ComboRol;
    private javax.swing.JComboBox<String> ComboRolEditar;
    private javax.swing.JComboBox<String> ComboUsuarioEliminar;
    private javax.swing.JComboBox<String> ComboUsuarioaEditar;
    private javax.swing.JMenu JMenuPrincipal;
    private javax.swing.JLabel LabelDarDeBaja;
    private javax.swing.JLabel LabelTipoCesion;
    private javax.swing.JLabel LblCrearUsuario;
    private javax.swing.JLabel LblEditarUsuario;
    private javax.swing.JMenuItem MimtStock;
    private javax.swing.JMenuItem MitmCesion;
    private javax.swing.JMenuItem MitmDevolucion;
    private javax.swing.JMenuItem MitmEditar;
    private javax.swing.JMenuItem MitmSalir;
    private javax.swing.JMenuItem MitmVenta;
    private javax.swing.JTextField TxtContraseñaAnterior;
    private javax.swing.JTextField TxtContraseñaCrear;
    private javax.swing.JTextField TxtContraseñaEditar;
    private javax.swing.JTextField TxtUsuarioCrear;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
