/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import ServicioIU.InterfaceService;
import Servicios.ProductService;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author agust
 */
public class Venta extends javax.swing.JFrame {

    DefaultTableModel model;
    ProductService Ps;
    InterfaceService Ss;

    /**
     * Creates new form NewJFrame
     *
     * @throws java.lang.Exception
     */
    public Venta() throws Exception {
        this.Ss = new InterfaceService();
        this.Ps = new ProductService();
        initComponents();
        this.model = Ss.Display((DefaultTableModel) TableStockVenta.getModel(), Ps.Dao.listarTodos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TxtFieldId = new javax.swing.JTextField();
        TxtFieldDescripcion = new javax.swing.JTextField();
        TxtFieldMarca = new javax.swing.JTextField();
        LblId = new javax.swing.JLabel();
        LblDescripcion = new javax.swing.JLabel();
        LblMarca = new javax.swing.JLabel();
        LblValor = new javax.swing.JLabel();
        BtnBuscar = new javax.swing.JButton();
        BtnAgregar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableCarrito = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableStockVenta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        JMenuPrincipal = new javax.swing.JMenu();
        MitmVenta = new javax.swing.JMenuItem();
        MimtStock = new javax.swing.JMenuItem();
        MitmCesion = new javax.swing.JMenuItem();
        MitmDevolucion = new javax.swing.JMenuItem();
        MitmConsultas = new javax.swing.JMenuItem();
        MitmSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TxtFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldIdActionPerformed(evt);
            }
        });

        TxtFieldDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldDescripcionActionPerformed(evt);
            }
        });

        TxtFieldMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldMarcaActionPerformed(evt);
            }
        });

        LblId.setText("ID");

        LblDescripcion.setText("Descripcion");

        LblMarca.setText("Marca");

        LblValor.setText("Valor Total :");

        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        BtnAgregar.setText("Agregar");

        BtnEliminar.setText("Eliminar");

        TableCarrito.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        TableCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Marca", "Categoria", "Precio de compra", "Precio", "Stock", "Alerta stock", "Interes", "Indice"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableCarrito.setCellSelectionEnabled(true);
        TableCarrito.setFillsViewportHeight(true);
        TableCarrito.setGridColor(new java.awt.Color(153, 255, 153));
        TableCarrito.setInheritsPopupMenu(true);
        TableCarrito.setMinimumSize(new java.awt.Dimension(800, 600));
        TableCarrito.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(TableCarrito);

        TableStockVenta.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        TableStockVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Marca", "Categoria", "Precio de compra", "Precio", "Stock", "Alerta stock", "Interes", "Indice"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableStockVenta.setCellSelectionEnabled(true);
        TableStockVenta.setFillsViewportHeight(true);
        TableStockVenta.setGridColor(new java.awt.Color(153, 255, 153));
        TableStockVenta.setInheritsPopupMenu(true);
        TableStockVenta.setMinimumSize(new java.awt.Dimension(800, 600));
        TableStockVenta.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(TableStockVenta);

        jLabel1.setText("Consulta de stock");

        jLabel2.setText("Productos en el carrito ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblDescripcion)
                            .addComponent(LblMarca)
                            .addComponent(LblId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtFieldMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(TxtFieldDescripcion)
                                    .addComponent(TxtFieldId))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnEliminar)
                                    .addComponent(BtnBuscar)
                                    .addComponent(BtnAgregar)))
                            .addComponent(LblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblId))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LblDescripcion)
                                    .addComponent(TxtFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblMarca))
                                .addGap(16, 16, 16)
                                .addComponent(LblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(116, 116, 116)
                        .addComponent(BtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );

        JMenuPrincipal.setText("Panel de Opciones");

        MitmVenta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MitmVenta.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        MitmVenta.setText("Venta");
        MitmVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        MitmVenta.setDoubleBuffered(true);
        MitmVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MitmVentaActionPerformed(evt);
            }
        });
        JMenuPrincipal.add(MitmVenta);

        MimtStock.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MimtStock.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        MimtStock.setText("Stock");
        JMenuPrincipal.add(MimtStock);

        MitmCesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MitmCesion.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        MitmCesion.setText("Cesion");
        JMenuPrincipal.add(MitmCesion);

        MitmDevolucion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MitmDevolucion.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        MitmDevolucion.setText("Devolucion");
        JMenuPrincipal.add(MitmDevolucion);

        MitmConsultas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MitmConsultas.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        MitmConsultas.setText("Consultas");
        MitmConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MitmConsultasActionPerformed(evt);
            }
        });
        JMenuPrincipal.add(MitmConsultas);

        MitmSalir.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        MitmSalir.setText("Salir");
        JMenuPrincipal.add(MitmSalir);

        jMenuBar2.add(JMenuPrincipal);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MitmVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MitmVentaActionPerformed

    }//GEN-LAST:event_MitmVentaActionPerformed

    private void MitmConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MitmConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MitmConsultasActionPerformed

    private void TxtFieldMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldMarcaActionPerformed

    private void TxtFieldDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldDescripcionActionPerformed

    private void TxtFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldIdActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        List<Boolean> isnull = null;
        List<String> categoria = null;
        try {
            categoria.add("Id");
            categoria.add("Description");
            categoria.add("Blend");
            isnull.add(Ss.BooleanFilter(TxtFieldId.getText()));
            isnull.add(Ss.BooleanFilter(TxtFieldDescripcion.getText()));
            isnull.add(Ss.BooleanFilter(TxtFieldMarca.getText()));
            categoria = Ss.ConsultasProductos(isnull, categoria);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en la interface venta : " + e.getMessage());
        }
        model = Ss.Display((DefaultTableModel) TableStockVenta.getModel(), Ps.Dao.listarEspecificados(categoria));

    }//GEN-LAST:event_BtnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JMenu JMenuPrincipal;
    private javax.swing.JLabel LblDescripcion;
    private javax.swing.JLabel LblId;
    private javax.swing.JLabel LblMarca;
    private javax.swing.JLabel LblValor;
    private javax.swing.JMenuItem MimtStock;
    private javax.swing.JMenuItem MitmCesion;
    private javax.swing.JMenuItem MitmConsultas;
    private javax.swing.JMenuItem MitmDevolucion;
    private javax.swing.JMenuItem MitmSalir;
    private javax.swing.JMenuItem MitmVenta;
    private javax.swing.JTable TableCarrito;
    private javax.swing.JTable TableStockVenta;
    private javax.swing.JTextField TxtFieldDescripcion;
    private javax.swing.JTextField TxtFieldId;
    private javax.swing.JTextField TxtFieldMarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
