/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejerciciosmanejofoco.folder;

import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author agust
 */
public class ejercicio1 extends javax.swing.JFrame {
    InputMap inpupMap;
    ActionMap actionMap;
    ActionColor aAmarillo;
    ActionColor aAzul;
    ActionColor aRojo;

    /**
     * Creates new form ejercicio1
     */
    public ejercicio1() {
        this.aAmarillo = new ActionColor(
                "Amarillo", new ImageIcon("src\\Icons\\paleta-de-pinturaAmarilla.png/"), Color.YELLOW);
        this.aAzul = new ActionColor(
                "Azul", new ImageIcon("src\\Icons\\paleta-de-pinturaAzul.png/"), Color.BLUE);
        this.aRojo = new ActionColor(
                "Rojo", new ImageIcon("src\\Icons\\paleta-de-pinturaRojo.png/"), Color.RED);
        
        // aColor = new ActionColor(Amarillo, );
        initComponents();
        this.inpupMap = this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        this.actionMap=this.getRootPane().getActionMap();
        KeyStroke Krojo = KeyStroke.getKeyStroke("control R" );
        KeyStroke Kazul = KeyStroke.getKeyStroke("control A");
        KeyStroke Kamarrillo = KeyStroke.getKeyStroke("control Z");
         inpupMap.put(Krojo, "aRojo");
         inpupMap.put(Kamarrillo, "aAmarillo");
         inpupMap.put(Kazul, "aAzul");
         actionMap.put("aRojo", aRojo);
         actionMap.put("aAmarillo", aAmarillo);
         actionMap.put("aAzul",aAzul);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnAzul =  new JButton(aAzul);
        BtnAmarillo = new JButton(aAmarillo);
        BtnRojo = new JButton(aRojo);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnAzul.setText("Azul");
        BtnAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAzulActionPerformed(evt);
            }
        });

        BtnAmarillo.setText("Amarillo");
        BtnAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAmarilloActionPerformed(evt);
            }
        });

        BtnRojo.setText("Rojo");
        BtnRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRojoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(BtnAzul)
                .addGap(50, 50, 50)
                .addComponent(BtnAmarillo)
                .addGap(48, 48, 48)
                .addComponent(BtnRojo)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnRojo)
                    .addComponent(BtnAmarillo)
                    .addComponent(BtnAzul))
                .addContainerGap(248, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void BtnAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAmarilloActionPerformed
       
    }//GEN-LAST:event_BtnAmarilloActionPerformed

    private void BtnRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRojoActionPerformed
    }//GEN-LAST:event_BtnRojoActionPerformed

    private void BtnAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAzulActionPerformed
   
    }//GEN-LAST:event_BtnAzulActionPerformed

    /**
     * @param args the command line arguments
     */
   // public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> {
        //    new ejercicio1().setVisible(true);
       // });
    //}
public class ActionColor extends AbstractAction{

    public ActionColor(String nombre, Icon iconoCOlor, Color colorBoton ) {
        putValue(Action.NAME, nombre );
        putValue(Action.SMALL_ICON , iconoCOlor);
        putValue(Action.SHORT_DESCRIPTION, "Poner la pagina del color : "+nombre);
        putValue("COLORDEFONDO", colorBoton);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
     Color C = (Color)getValue("COLORDEFONDO");
        jPanel1.setBackground(C);
    }}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAmarillo;
    private javax.swing.JButton BtnAzul;
    private javax.swing.JButton BtnRojo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
